data-dir: /opt/pandoc
from: markdown
listings: true
dpi: 75
variables:
  lang: en
  fontsize: 10pt
  toc-own-page: true
  footnotes-pretty: true
  table-use-row-colors: true
  table-row-color: "22FFFF"
  table-row-height: 142pt
  table-column-color: "22FF33"

