---
title:
  - type: main
    text: Resume
  - type: subtitle
    text: Johanna Doe
subject: "Consultant, Architect, Developer, Trainer"
keywords:
  - Resume
  - Consultant
  - Architect
  - Developer
lang: "en"
creator:
  - role: author
    text: Johanna Doe
identifier:
  - scheme: DOI
    text: doi:10.234234.234/33
author:
  - Johanna Doe

belongs-to-collection: resume
description: Application document for Johanna Doe
publisher:  vergissberlin
rights: © 2022 Johanna Doe, CC BY-NC
